[supervisord]
nodaemon=true
user=root

[program:nginx]
command=/usr/sbin/nginx -g 'daemon off;'
autorestart=true
stdout_logfile=/var/log/nginx.log
stderr_logfile=/var/log/nginx_err.log

[program:rails]
command=bundle exec rails server -b 127.0.0.1
autorestart=true
stdout_logfile=/var/log/rails.log
stderr_logfile=/var/log/rails_err.log